# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: Charry's Github Blog
url: http://charryli.github.io
feed: /atom.xml
author_info: <a href="http://charryli.github.io/">CharryLi</a>

myblog:
  gavatar: images/2.jpg
  gpname: charryli
  linkedin: 
  github: https://github.com/charryli
  email: mailto:taotao.engineer@gmail.com
  coverimgs: []
  postbgimg: []

categories: [python, books]
